### ISSUE TITLE
Proposal Feedback

### ISSUE THREAD

**Issue by stephenjarrell19** [COGS118A/Group009-Sp22#1]
Total Points: 7.75/8

Title & Abstract (0.75/1)
Try to include information about what models you will use. Also, use active voice, not passive voice! ("We will train a variety of classifiers...", instead of "Different classification algorithms will be trained")

Also your problem statement and abstract are a little bit different; its not perfectly clear to me what you want these models to predict. Are you predicting risk ("potentially having heart disease") or diagnosing like what is implied in the abstract? It's semantics, but I want you to be as clear as possible in your description of what you intend to do.

Background (1/1)
This is good!

Problem Statement (1/1)
Good but fix some typos here!

Data (1/1)
Good!

Proposed Solution (1/1)
Happy to see a thorough description here. Great job.

Metrics (1/1)
Nice.

Ethics & Privacy (1/1)
This is good.

Team Expectations + Timeline (1/1)
Also good.

You can reply to this feedback below. Contact me anytime if you want help improving your project or have any questions at all!

**Comment by chc012** [comment]
Thanks!
