### ISSUE TITLE
Checkpoint Feedback

### ISSUE THREAD

**Issue by stephenjarrell19** [COGS118A/Group009-Sp22#2]
**Total Points: 8 / 8 points**

Project Question/Goal (out of 1): 1/1 points

_Criteria:_
- Clear/Unambiguous in its wording
- Achievable
- Well-specified 

Data (out of 1): 1/1 points

_Criteria:_
- Have at least one dataset 
- Appropriate to the question/goal
- Large enough datapoints ~5 to 10k
- Enough variables to be interesting ~10
- Not m>=n

Data Manipulation (out of 4): 4/4 points
Can you also train your models on a subset of features instead of just principal components via PCA? Then compare the results.

_Criteria:_
  - Cleaned
  - Explored
  - Demonstrate suitability
  - Appropriately transformed (stdscaler, text processing)
  - Identified a subset of features

Baseline Performance /  Preliminary Results (out of 2):  2/2 points

Good enough so far.

_Criteria:_
- Baseline
- Learning curves
- Validation curves
- Performance across models

Other Notes for the Final Submission:
Please keep doing what you're doing! I love it.

When you work on your final, make sure you are explaining your approaches, comparing them, and reasoning about why some may be better. Ex.: Why do particular models seem to do well or poorly? 

What is your process for selecting the best model? Are you purely using metrics, or do you have computational efficiency and parsimony principle in mind? Just be clear, there's no "right answer" here. However, you should be performing hyperparameter tuning, potentially with some form of Grid Search and Cross Validation.

EXCELLENT work.

**Comment by chc012** [comment]
Hey @stephenjarrell19, thanks a lot for the feedback!
One thing you mentioned is that we should 

> train your models on a subset of features instead of just principal components via PCA? Then compare the results.

which I think means that you may have missed the part that we did this, in the first part of the feature selection paragraph before PCA.
Sorry to bug you over this but I was hoping that you can check this part out to see if we are actually doing this right.

**Comment by chc012** [comment]
Thanks y'all!
